In [3]:
import torch
torch.load('models_diff/tabpfn__emsize_512_nlayers_12_steps_2048_bs_32ada_lr_0.0001_1_gpu_07_24_2023_01_43_33_nooptimizer_epoch_1650.cpkt')

(OrderedDict([('transformer_encoder.layers.0.self_attn.in_proj_weight',
               tensor([[ 0.0201, -0.0106,  0.0218,  ...,  0.0414,  0.0084, -0.0290],
                       [ 0.0182,  0.0171,  0.0018,  ..., -0.0450,  0.0209, -0.0557],
                       [ 0.0069, -0.0595,  0.0247,  ...,  0.0204, -0.0388,  0.0199],
                       ...,
                       [-0.0282, -0.0170,  0.0267,  ...,  0.0237, -0.0432, -0.0274],
                       [-0.0182, -0.0265, -0.0297,  ..., -0.0179, -0.0446, -0.0032],
                       [ 0.0121,  0.0520,  0.0040,  ..., -0.0057,  0.0539, -0.0365]],
                      device='cuda:2')),
              ('transformer_encoder.layers.0.self_attn.in_proj_bias',
               tensor([ 0.0214,  0.0499,  0.0502,  ..., -0.0011, -0.0141,  0.0069],
                      device='cuda:2')),
              ('transformer_encoder.layers.0.self_attn.out_proj.weight',
               tensor([[ 0.0046,  0.0090,  0.0125,  ..., -0.0321,  0.0171,  0.01

Bad pipe message: %s [b'\\\xee\x99\xcfG[\x1d\xe7f\xb9y\xcdoh\x83\nnb \xc9S\xf1q?\x87q\xea-\x10p\xe3\xdff\x92\xb8]\x14\\\x19F\xd0[sne=\xb0k\xfaK>\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19']
Bad pipe message: %s [b"\x82\xa1\xcb\xae\xa6\x05!G\x95\x03%\xba\x9e\xea+\xc1\x86\xf9 D\x8f\x8e\\\x9a\x9c\xa5\x15\xb3\x99|ZI['\x832aa\\\xb1\xbc\xa0\xfa\xd7\xf2m\x8e>3T\\\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03"]
Bad pipe message: %s [b'\x08\x08\x08\t\x08\n\x08', b'\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06']
Bad pipe message: %s [b'']
Bad pipe message: %s [b'\x03\x02\x03\x04\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d\x00 \x8c\